# Generated by Django 5.0.7 on 2024-08-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_course', models.CharField(max_length=50)),
                ('service_about', models.CharField(max_length=50)),
            ],
        ),
    ]
